### ISSUE TITLE
`OrderedImports` sometimes moves import before file header

### ISSUE THREAD

**Issue by FranzBusch** [swiftlang/swift-format#772]
When the file has a header comment e.g. for licensing purposes and there is no new line between the file header and the import statement then `OrderedImports` will sometimes result in the import being moved before the file header.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://131992539

**Comment by allevato** [comment]
Do you have an example where this happened?

The first thing that comes to mind is that we require a blank line between the file header and the first import, because comments _immediately_ preceding an import are assumed to be attached to that import. So these examples would reorder differently:

```swift
// foo
// bar
import quux
import baz
```
becomes
```swift
import baz
// foo
// bar
import quux
```

But

```swift
// foo
// bar

import quux
import baz
```
becomes
```swift
// foo
// bar

import baz
import quux
```

**Comment by FranzBusch** [comment]
Your example is exactly right. Our case is that we have some license headers at the top of the file and we had some files that didn't have a new line between the header comment and the import. Now we fixed this with just adding that new lines manually but I am wondering if we can make the `OrderedImports` rule smart here to detect license headers in some way.

**Comment by allevato** [comment]
One option would be to treat any comment at the top of a file like a special case and keep it there, but that would break simple cases that don't use file headers like

```swift
// This import does something import-ant.
import Foo
import Bar
```

I'm not sure how successful it would be to try to detect file headers, since they don't really have to have specific formats or contents either.

Given all that potential complexity and it being unlikely that we could distinguish a file header from a comment that just happens to be on the first line, it seems like just requiring a blank line is the cleanest way forward. I'm open to other ideas, though.

**Comment by FranzBusch** [comment]
FWIW I am okay with just requiring this manual blank line. We can close this issue if you want

**Comment by allevato** [comment]
SGTM, thanks!
