### ISSUE TITLE
Access control on extensions is being removed and added to methods as `fileprivate`

### ISSUE THREAD

**Issue by erezhodsam** [swiftlang/swift-format#877]
Consider the following extension code:

```swift
private extension StorageRepository {
    func absolutelyPrivateMethod() { ... }
}
```

When applying `swift-format`, it is being modified to:

```swift
extension StorageRepository {
    fileprivate func absolutelyPrivateMethod() { ... }
}
```

A very weird behavior. Is there a way to make `swift-format` behavior respect the access control on extensions? Also, why `fileprivate` and not just `private`?

Thanks!

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://139589988

**Comment by erezhodsam** [comment]
I’ve discovered a solution to this problem. To implement it, add this to the `.swift-format` rules file:
```json
"rules": {
    "NoAccessLevelOnExtensionDeclaration": false
}
```
It will simply ignore access level declarations on extensions. There's still the issue of it turning into a `fileprivate` instead of preserving the original declaration when this rule is set to `true`.

**Comment by allevato** [comment]
> It will simply ignore access level declarations on extensions. There's still the issue of it turning into a `fileprivate` instead of preserving the original declaration when this rule is set to `true`.

Using `fileprivate` here is what actually preserves the correct semantics.

At file scope, `private` and `fileprivate` are identical. This applies to extensions as well; the effective access level is based on how it is computed from the declaration to which the keyword is originally applied, not by simple keyword substitution upon all of its members.

Here's an example:

```swift
struct S {
    private func f() { T().g() }
}
struct T {}
private extension T {
    func g() {}
}
```
This compiles successfully, because `private extension T` implies `fileprivate` access for all of its members.

If you change the extension by simply moving `private` inside:

```swift
extension T {
    private func g() {}
}
```

Then it no longer compiles: `<source>:3:13: error: 'g' is inaccessible due to 'private' protection level`
